version: "3.9"
services:
  server:
    build: ./server
    container_name: wealthwise-server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - ./server/.env 
      
  client:
    build: ./client
    container_name: wealthwise-client
    ports:
      - "3000:80"
    depends_on:
      - server
